repos:
  - repo: local
    hooks:
      - id: typescript-check
        name: Check types
        entry: pnpm tsc
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
      - id: prettier
        name: Check formatting
        entry: pnpm prettier --ignore-unknown --write
        language: system
        exclude: pnpm-lock.yaml
